export const productsData = [
  {
    id: 1,
    name: "Purified Shilajit",
    image: "https://m.media-amazon.com/images/I/81OW3f7g7YL._SL1500_.jpg",
    price: 359,
    originalPrice: 449,
    discount: 20,
    rating: 5,
    category: "PERFORM BETTER",
    sharkTank: true,
  },
  {
    id: 2,
    name: "Gokshura Drops",
    image: "https://merlionnaturals.in/cdn/shop/products/GotuKola_1_1600x.jpg?v=1671703256",
    price: 549,
    originalPrice: 699,
    discount: 21,
    rating: 4.5,
    category: "LAST LONGER",
    sharkTank: true,
  },
  {
    id: 3,
    name: "Ashwagandha Capsules",
    image: "https://m.media-amazon.com/images/I/81OW3f7g7YL._SL1500_.jpg",
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 4.7,
    category: "PERFORM BETTER",
    sharkTank: false,
  },
  {
    id: 4,
    name: "Kesar Infused Honey",
    image: "https://m.media-amazon.com/images/I/81OW3f7g7YL._SL1500_.jpg",
    price: 699,
    originalPrice: 899,
    discount: 22,
    rating: 4.8,
    category: "BEST SELLER",
    sharkTank: false,
  },
  {
    id: 5,
    name: "ManPower Combo Pack",
    image: "https://m.media-amazon.com/images/I/81OW3f7g7YL._SL1500_.jpg",
    price: 1199,
    originalPrice: 1499,
    discount: 20,
    rating: 4.3,
    category: "COMBOS FOR ALPHA MEN",
    sharkTank: true,
  },
  {
    id: 6,
    name: "Ayurvedic Testosterone Booster",
    image: "https://m.media-amazon.com/images/I/81OW3f7g7YL._SL1500_.jpg",
    price: 449,
    originalPrice: 599,
    discount: 25,
    rating: 4.4,
    category: "BETTER ERECTIONS",
    sharkTank: false,
  },
  {
    id: 7,
    name: "Vitality Power Syrup",
    image: "https://m.media-amazon.com/images/I/81OW3f7g7YL._SL1500_.jpg",
    price: 275,
    originalPrice: 350,
    discount: 21,
    rating: 4.2,
    category: "PERFORM BETTER",
    sharkTank: false,
  },
  {
    id: 8,
    name: "Natural Delay Spray",
    image: "https://m.media-amazon.com/images/I/81OW3f7g7YL._SL1500_.jpg",
    price: 199,
    originalPrice: 249,
    discount: 20,
    rating: 3.8,
    category: "LAST LONGER",
    sharkTank: true,
  },
  {
    id: 9,
    name: "Intimacy Oil",
    image: "https://m.media-amazon.com/images/I/81OW3f7g7YL._SL1500_.jpg",
    price: 320,
    originalPrice: 400,
    discount: 20,
    rating: 4.0,
    category: "BETTER ERECTIONS",
    sharkTank: true,
  },
  {
    id: 10,
    name: "Alpha Men Essentials Kit",
    image: "https://m.media-amazon.com/images/I/81OW3f7g7YL._SL1500_.jpg",
    price: 1499,
    originalPrice: 1999,
    discount: 25,
    rating: 4.9,
    category: "COMBOS FOR ALPHA MEN",
    sharkTank: false,
  },
  {
    id: 11,
    name: "Ayurvedic Tonic for Stamina",
    image: "https://merlionnaturals.in/cdn/shop/products/GotuKola_1_1600x.jpg?v=1671703256",
    price: 350,
    originalPrice: 420,
    discount: 16,
    rating: 4.1,
    category: "PERFORM BETTER",
    sharkTank: false,
  },
  {
    id: 12,
    name: "Men's Herbal Capsules",
    image: "https://merlionnaturals.in/cdn/shop/products/GotuKola_1_1600x.jpg?v=1671703256",
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 4.3,
    category: "BETTER ERECTIONS",
    sharkTank: false,
  },
  {
    id: 13,
    name: "Gold Vitality Combo",
    image: "https://merlionnaturals.in/cdn/shop/products/GotuKola_1_1600x.jpg?v=1671703256",
    price: 999,
    originalPrice: 1299,
    discount: 23,
    rating: 4.6,
    category: "COMBOS FOR ALPHA MEN",
    sharkTank: true,
  },
  {
    id: 14,
    name: "Shark Tank Energy Booster",
    image: "https://merlionnaturals.in/cdn/shop/products/GotuKola_1_1600x.jpg?v=1671703256",
    price: 599,
    originalPrice: 749,
    discount: 20,
    rating: 4.8,
    category: "BEST SELLER",
    sharkTank: true,
  },
  {
    id: 15,
    name: "Performance Energy Mix",
    image: "https://merlionnaturals.in/cdn/shop/products/GotuKola_1_1600x.jpg?v=1671703256",
    price: 499,
    originalPrice: 649,
    discount: 23,
    rating: 4.4,
    category: "PERFORM BETTER",
    sharkTank: true,
  },
  {
    id: 16,
    name: "Natural Stamina Capsules",
    image: "https://merlionnaturals.in/cdn/shop/products/GotuKola_1_1600x.jpg?v=1671703256",
    price: 350,
    originalPrice: 450,
    discount: 22,
    rating: 4.2,
    category: "LAST LONGER",
    sharkTank: false,
  },
  {
    id: 17,
    name: "Instant Energy Sachets",
    image: "https://merlionnaturals.in/cdn/shop/products/GotuKola_1_1600x.jpg?v=1671703256",
    price: 275,
    originalPrice: 349,
    discount: 21,
    rating: 4.3,
    category: "BEST SELLER",
    sharkTank: false,
  },
  {
    id: 18,
    name: "Testosterone Pro Formula",
    image: "https://merlionnaturals.in/cdn/shop/products/GotuKola_1_1600x.jpg?v=1671703256",
    price: 749,
    originalPrice: 999,
    discount: 25,
    rating: 4.5,
    category: "BETTER ERECTIONS",
    sharkTank: true,
  },
  {
    id: 19,
    name: "Combo Stamina Max Pack",
    image: "https://merlionnaturals.in/cdn/shop/products/GotuKola_1_1600x.jpg?v=1671703256",
    price: 1299,
    originalPrice: 1699,
    discount: 24,
    rating: 4.7,
    category: "COMBOS FOR ALPHA MEN",
    sharkTank: false,
  },
  {
    id: 20,
    name: "Men's Ayurvedic Kit",
    image: "https://merlionnaturals.in/cdn/shop/products/GotuKola_1_1600x.jpg?v=1671703256",
    price: 899,
    originalPrice: 1199,
    discount: 25,
    rating: 4.4,
    category: "BEST SELLER",
    sharkTank: true,
  },
];
